# Generated by Django 5.1.4 on 2026-06-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=60)),
                ('mfg_date', models.DateField(blank=True, null=True, verbose_name='Manufacturing date')),
                ('expiry_date', models.DateField(db_index=True)),
                ('quantity', models.IntegerField(default=0)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MRP')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=300, verbose_name='Generic / composition')),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=10, verbose_name='HSN code')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('schedule', models.CharField(choices=[('OTC', 'OTC (over the counter)'), ('H', 'Schedule H'), ('H1', 'Schedule H1'), ('X', 'Schedule X')], default='OTC', max_length=3)),
                ('pack_unit', models.CharField(blank=True, help_text='e.g. "Strip of 10", "Bottle 100ml"', max_length=40)),
                ('rack_location', models.CharField(blank=True, max_length=40)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('reorder_qty', models.PositiveIntegerField(default=50)),
                ('min_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('max_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('purchase', 'Goods receipt'), ('sale', 'Sale'), ('sale_return', 'Sales return'), ('purchase_return', 'Purchase return'), ('damage', 'Damage'), ('expiry', 'Expiry write-off'), ('count', 'Count correction')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('actor', models.CharField(default='counter', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
