# Generated by Django 5.1.4 on 2026-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reversed',
            field=models.BooleanField(default=False),
        ),
    ]
