# Generated by Django 5.1.4 on 2026-06-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_reversed'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='loose_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='med_type',
            field=models.CharField(choices=[('tablet', 'Tablet / capsule'), ('syrup', 'Syrup / liquid'), ('injection', 'Injection'), ('drops', 'Drops'), ('ointment', 'Ointment / cream'), ('commercial', 'Commercial product'), ('other', 'Other')], default='tablet', max_length=12, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
