# Generated by Django 5.1.4 on 2026-06-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('detail', models.TextField(blank=True)),
                ('actor', models.CharField(default='counter', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('low_stock', 'Low stock'), ('out_of_stock', 'Out of stock'), ('near_expiry', 'Near expiry'), ('reorder', 'Reorder')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(max_length=120, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Sri Sakthi Medicals', max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('drug_licence_no', models.CharField(blank=True, max_length=60, verbose_name='Drug licence no.')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('near_expiry_days', models.PositiveIntegerField(default=90, help_text='Warn when a batch expires within this many days.')),
                ('default_reorder_level', models.PositiveIntegerField(default=10)),
                ('default_reorder_qty', models.PositiveIntegerField(default=50)),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('admin_password', models.CharField(blank=True, max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop setting',
                'verbose_name_plural': 'Shop settings',
            },
        ),
    ]
