# Generated by Django 5.1.4 on 2026-06-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsetting',
            name='has_drug_license',
            field=models.BooleanField(default=True, verbose_name='Has medical supply licence'),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=12, verbose_name='Invoice number prefix'),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='po_next_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopsetting',
            name='po_prefix',
            field=models.CharField(default='PO', max_length=12, verbose_name='PO number prefix'),
        ),
    ]
