# Generated by Django 5.1.4 on 2026-06-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('credit', 'Credit / khata')], default='cash', max_length=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('credit', 'On credit'), ('returned', 'Returned')], default='paid', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CGST')),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SGST')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('irn', models.CharField(blank=True, max_length=64, verbose_name='IRN')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('actor', models.CharField(default='counter', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(blank=True, max_length=10, verbose_name='HSN')),
                ('batch_number', models.CharField(blank=True, max_length=60)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MRP')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
