# Generated by Django 5.1.4 on 2026-06-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='unit_mode',
            field=models.CharField(default='pack', max_length=6),
        ),
    ]
