# Generated by Django 5.1.4 on 2026-06-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Next day", "2-3 days".', max_length=60, unique=True)),
                ('days', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['days'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('days', models.PositiveIntegerField(default=0, help_text='Credit period in days (0 = immediate).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Supplier code'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='drug_license_no',
            field=models.CharField(blank=True, max_length=60, verbose_name='Drug licence no.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='has_drug_license',
            field=models.BooleanField(default=False, verbose_name='Has medical supply licence'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lead_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='purchasing.leadtime'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='purchasing.paymentterm'),
        ),
    ]
