# Generated by Django 5.1.4 on 2026-06-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='drug_license_no',
            field=models.CharField(blank=True, max_length=60, verbose_name='Drug licence no.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_drug_license',
            field=models.BooleanField(default=False, verbose_name='Has medical supply licence'),
        ),
    ]
